services:
  db:
    container_name: postgres
    image: docker.io/library/postgres:16.3-alpine3.20
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

    shm_size: 128mb

    volumes:
      - ~/.volumes/name/db:/pg-data:Z
    # - ~/.volumes/name:/app/.neiroaxum_server/vault:Z
    ports:
      - "5433:5432"
    expose:
      - "5433"
    environment:
      POSTGRES_DB: "appointme-db"
      POSTGRES_PASSWORD: "change-password"
      PGDATA: /pg-data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
